name: "Codeship Environment Variable Adapter"
description: "Use Codeship environment variables in your workflow"
branding:
  icon: life-buoy
  color: orange
inputs:
  github-token:
    description: 'GitHub token with permissions look up commit and pull request details'
    required: false
  project-id:
    description: (optional) Codeship project id
    required: false
runs:
  using: "node20"
  main: "lib/index.js"
