name: "Codeship Environment Variable Adapter"
description: "Use Codeship environment variables in your workflow"
branding:
  icon: life-buoy
  color: orange
inputs:
  project-id:
    description: (optional) Codeship project id
    required: false
runs:
  using: "node20"
  main: "lib/index.js"
