name: "Codeship Environment Variable Adapter"
description: "Use Codeship environment variables in your workflow"
branding:
  icon: life-buoy
  color: orange
inputs:
  github-token:
    description: 'Optional: GitHub token with permissions to look up commit and pull request details so that CI_COMMIT_MESSAGE is populated with the HEAD commit message'
    required: false
  project-id:
    description: (optional) Codeship project id
    required: false
runs:
  using: "node20"
  main: "lib/index.js"
