"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var EnvironmentVariables;
(function (EnvironmentVariables) {
    EnvironmentVariables["CI"] = "CI";
    EnvironmentVariables["CI_BRANCH"] = "CI_BRANCH";
    EnvironmentVariables["CI_BUILD_APPROVED"] = "CI_BUILD_APPROVED";
    EnvironmentVariables["CI_BUILD_ID"] = "CI_BUILD_ID";
    EnvironmentVariables["CI_COMMITTER_EMAIL"] = "CI_COMMITTER_EMAIL";
    EnvironmentVariables["CI_COMMITTER_NAME"] = "CI_COMMITTER_NAME";
    EnvironmentVariables["CI_COMMITTER_USERNAME"] = "CI_COMMITTER_USERNAME";
    EnvironmentVariables["CI_COMMIT_DESCRIPTION"] = "CI_COMMIT_DESCRIPTION";
    EnvironmentVariables["CI_COMMIT_ID"] = "CI_COMMIT_ID";
    EnvironmentVariables["CI_COMMIT_MESSAGE"] = "CI_COMMIT_MESSAGE";
    EnvironmentVariables["CI_NAME"] = "CI_NAME";
    EnvironmentVariables["CI_PROJECT_ID"] = "CI_PROJECT_ID";
    EnvironmentVariables["CI_PR_NUMBER"] = "CI_PR_NUMBER";
    EnvironmentVariables["CI_PULL_REQUEST"] = "CI_PULL_REQUEST";
    EnvironmentVariables["CI_REPO_NAME"] = "CI_REPO_NAME";
    EnvironmentVariables["CI_STRING_TIME"] = "CI_STRING_TIME";
    EnvironmentVariables["CI_TIMESTAMP"] = "CI_TIMESTAMP";
})(EnvironmentVariables = exports.EnvironmentVariables || (exports.EnvironmentVariables = {}));
