export enum EnvironmentVariables {
  CI = 'CI',
  CI_BRANCH = 'CI_BRANCH',
  CI_BUILD_APPROVED = 'CI_BUILD_APPROVED',
  CI_BUILD_ID = 'CI_BUILD_ID',
  CI_COMMITTER_EMAIL = 'CI_COMMITTER_EMAIL',
  CI_COMMITTER_NAME = 'CI_COMMITTER_NAME',
  CI_COMMITTER_USERNAME = 'CI_COMMITTER_USERNAME',
  CI_COMMIT_DESCRIPTION = 'CI_COMMIT_DESCRIPTION',
  CI_COMMIT_ID = 'CI_COMMIT_ID',
  CI_COMMIT_MESSAGE = 'CI_COMMIT_MESSAGE',
  CI_NAME = 'CI_NAME',
  CI_PROJECT_ID = 'CI_PROJECT_ID',
  CI_PR_NUMBER = 'CI_PR_NUMBER', // or blank
  CI_PULL_REQUEST = 'CI_PULL_REQUEST', // URL or false
  CI_REPO_NAME = 'CI_REPO_NAME',
  CI_STRING_TIME = 'CI_STRING_TIME',
  CI_TIMESTAMP = 'CI_TIMESTAMP',
}